### PR TITLE
Handle nil render for binary

### LINKED ISSUE #170: Kino Explorer vulnerable to nil in binary column type.
Kino works fine with nils in the `:string` type, but falls over with the `:binary` type.

So, in a Livebook, the following works when Kino renders the cell
```elixir
DF.new(a: [nil, "Foo"])
```

But the following fails:
```elixir
DF.new([a: [nil, "Foo"]], dtypes: %{"a" => :binary})
```

It fails with the following exception:
```
** (FunctionClauseError) no function clause matching in String.printable?/2
    (elixir 1.17.1) lib/string.ex:322: String.printable?(nil, 50)
    (kino_explorer 0.1.21) lib/kino/explorer.ex:156: Kino.Explorer.value_to_string/2
    (elixir 1.17.1) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (kino_explorer 0.1.21) lib/kino/explorer.ex:77: Kino.Explorer.get_data/2
    (kino 0.13.2) lib/kino/table.ex:202: Kino.Table.get_content/1
    (kino 0.13.2) lib/kino/table.ex:128: Kino.Table.handle_connect/1
    (kino 0.13.2) lib/kino/js/live/server.ex:106: Kino.JS.Live.Server.call_handle_info/3
    (kino 0.13.2) lib/kino/js/live/server.ex:71: Kino.JS.Live.Server.handle_info/2
```

It seems this line chokes when trying to guard against unprintable characters: https://github.com/livebook-dev/kino_explorer/blob/74461a97d315050ff8b2b3759e3a8ed0cbeb6cff/lib/kino/explorer.ex#L156

I ran into this because I have found some Parquet files will load strings as `:binary` instead of `:string`. My example is contrived to trigger the error, but it happens when for example I try to read Parquet files from Clickhouse. The metadata is slightly different between one generated by `polars` vs `parquet-cpp`

```
$> parquet meta example-polars.parquet
File path:  example-polars.parquet
Created by: parquet-cpp version 1.5.1-SNAPSHOT
Properties: (none)
Schema:
message schema {
    optional binary foo;
}
```

versus

```
$> parquet meta example-clickhouse.parquet
File path:  example-clickhouse.parquet
Created by: Polars
Properties:
  ARROW:schema: /////2oAAAAEAAAA8v///xQAAAAEAAEAAAAKAAsACAAKAAQA+P///wwAAAAIAAgAAAAEAAEAAAAEAAAA7P///ywAAAAgAAAAGAAAAAEUAAAQABIABAAQABEACAAAAAwAAAAAAPz///8EAAQAAQAAAGEA
Schema:
message root {
  optional binary foo (STRING);
}
```

### PR DESCRIPTION
**Pull request by brendon9x**
Closes #170 

Added a nil guard and a test. I thought adding tests for all types but it didn't look like this repo has those vibes.

### CODE REVIEW

File: lib/kino/explorer.ex [hunk 1]
```diff
@@ -151,6 +151,8 @@ defmodule Kino.Explorer do
     end)
   end
 
+  defp value_to_string("binary", value) when is_nil(value), do: to_string(value)
```
Comment (josevalim) [inline lib/kino/explorer.ex:154]:
```suggestion
  defp value_to_string(_, value) when is_nil(value), do: ""
```

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
